on: 
  push:
    paths-ignore:
      - 'cli/**'

name: verify cli

jobs:
  verify_cli:
    name: verify cli
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '

  build_cli:
    name: build cli
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '