name: test tags

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - 'test'
    tags:
      - '*' 
  workflow_dispatch:
    inputs:
      ref:
        description: "Why trigger?"
        required: true 
        type: string

jobs:
  test:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: test tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo ${{ github.ref_name }}

      - name: test 
        run: |
          echo ${{ github.ref_name }}
